# Generated by Django 4.1 on 2022-09-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sobre_Nosotros',
        ),
        migrations.DeleteModel(
            name='Turnos',
        ),
    ]
