# Generated by Django 4.1 on 2022-09-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospital', '0002_servicios_delete_sobre_nosotros_delete_turnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=20)),
                ('texto', models.CharField(max_length=1000000000)),
                ('autor', models.CharField(max_length=10)),
                ('imagen', models.ImageField(upload_to='')),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
        migrations.DeleteModel(
            name='Pacientes',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
