# Generated by Django 4.1 on 2022-09-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospital', '0003_publicacion_delete_empleados_delete_pacientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
