# Generated by Django 4.1 on 2022-09-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospital', '0004_alter_publicacion_fecha_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
