# Generated by Django 4.1 on 2022-09-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospital', '0011_comentario_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
